package com.ishuyin.gecollsn.green;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ishuyin.gecollsn.accueilBlock.domain.BookInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_INFO".
*/
public class BookInfoDao extends AbstractDao<BookInfo, Long> {

    public static final String TABLENAME = "BOOK_INFO";

    /**
     * Properties of entity BookInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Thumb = new Property(2, String.class, "thumb", false, "THUMB");
        public final static Property BookPlayer = new Property(3, String.class, "bookPlayer", false, "BOOK_PLAYER");
        public final static Property LatestUpdate = new Property(4, String.class, "latestUpdate", false, "LATEST_UPDATE");
        public final static Property BookDownloadUrl = new Property(5, String.class, "bookDownloadUrl", false, "BOOK_DOWNLOAD_URL");
        public final static Property CreateTime = new Property(6, String.class, "createTime", false, "CREATE_TIME");
        public final static Property Type = new Property(7, int.class, "type", false, "TYPE");
    }


    public BookInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BookInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"THUMB\" TEXT," + // 2: thumb
                "\"BOOK_PLAYER\" TEXT," + // 3: bookPlayer
                "\"LATEST_UPDATE\" TEXT," + // 4: latestUpdate
                "\"BOOK_DOWNLOAD_URL\" TEXT," + // 5: bookDownloadUrl
                "\"CREATE_TIME\" TEXT," + // 6: createTime
                "\"TYPE\" INTEGER NOT NULL );"); // 7: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(3, thumb);
        }
 
        String bookPlayer = entity.getBookPlayer();
        if (bookPlayer != null) {
            stmt.bindString(4, bookPlayer);
        }
 
        String latestUpdate = entity.getLatestUpdate();
        if (latestUpdate != null) {
            stmt.bindString(5, latestUpdate);
        }
 
        String bookDownloadUrl = entity.getBookDownloadUrl();
        if (bookDownloadUrl != null) {
            stmt.bindString(6, bookDownloadUrl);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(7, createTime);
        }
        stmt.bindLong(8, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(3, thumb);
        }
 
        String bookPlayer = entity.getBookPlayer();
        if (bookPlayer != null) {
            stmt.bindString(4, bookPlayer);
        }
 
        String latestUpdate = entity.getLatestUpdate();
        if (latestUpdate != null) {
            stmt.bindString(5, latestUpdate);
        }
 
        String bookDownloadUrl = entity.getBookDownloadUrl();
        if (bookDownloadUrl != null) {
            stmt.bindString(6, bookDownloadUrl);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(7, createTime);
        }
        stmt.bindLong(8, entity.getType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BookInfo readEntity(Cursor cursor, int offset) {
        BookInfo entity = new BookInfo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thumb
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bookPlayer
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // latestUpdate
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bookDownloadUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // createTime
            cursor.getInt(offset + 7) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookInfo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThumb(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBookPlayer(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLatestUpdate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBookDownloadUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreateTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setType(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
